name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Navigate to src dir
        run: |
          cd "reversi_src/src"

      - name: Compile Java file
        run: |
          javac -d Reversi.java cs3500/reversi/**/*.java

      - name: Create manifest
        run: |
          echo "Main-Class: Reversi" > manifest.txt

      - name: Package JAR
        run: |
          jar cfm Reversi.jar manifest.txt Reversi.class cs3500/reversi/**/*.class

      - name: Move JAR to root directory
        run: |
          mv Reversi.jar ../../Reversi.jar
          cd ../..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Reversi.jar
          generate_release_notes: true
