name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java file
        working-directory: ./reversi_src/src
        run: |
          find . -name "*.java" > sources.txt
          javac -d . @sources.txt

      - name: Create manifest
        working-directory: ./reversi_src/src
        run: |
          echo "Main-Class: Reversi" > manifest.txt

      - name: Package JAR
        working-directory: ./reversi_src/src
        run: |
          jar cfm Reversi.jar manifest.txt $(find . -name "*.class")

      - name: Move JAR to root directory
        run: |
          mv reversi_src/src/Reversi.jar Reversi.jar
          cd ../..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Reversi.jar
          generate_release_notes: true
